-- 17. Avec le même type de sélection que ci-dessus, sortir un total des stocks par
-- fournisseur trié par total décroissant

SELECT FOURNIS.NOMFOU, PRODUIT.CODART, PRODUIT.LIBART, PRODUIT.STKPHY, PRODUIT.UNIMES
FROM FOURNIS
INNER JOIN VENTE ON FOURNIS.NUMFOU = VENTE.NUMFOU
INNER JOIN PRODUIT ON VENTE.CODART = PRODUIT.CODART
WHERE PRODUIT.STKPHY <= PRODUIT.STKLE * 1.5
AND VENTE.DELLIV <= DATE_ADD(CURDATE(), INTERVAL 30 DAY)
ORDER BY FOURNIS.NOMFOU, PRODUIT.CODART