
SELECT FOURNIS.NOMFOU, SUM(PRODUIT.STKPHY) AS TOTAL_STOCK
FROM FOURNIS
INNER JOIN VENTE ON FOURNIS.NUMFOU = VENTE.NUMFOU
INNER JOIN PRODUIT ON VENTE.CODART = PRODUIT.CODART
WHERE PRODUIT.STKPHY <= PRODUIT.STKLE * 1.5
AND VENTE.DELLIV <= DATE_ADD(CURDATE(), INTERVAL 30 DAY)
GROUP BY FOURNIS.NUMFOU, FOURNIS.NOMFOU
ORDER BY TOTAL_STOCK DESC;